from dataclasses import dataclass, field
import pandas as pd
import numpy as np
from datetime import datetime

PARITY_THRESHOLD = 0.95  # Mandatory accuracy gate — do not lower this.

KNOWN_BUY_COLS  = {'buy', 'long', 'entry_long', 'signal_buy', 'bull'}
KNOWN_SELL_COLS = {'sell', 'short', 'entry_short', 'signal_sell', 'bear'}

@dataclass
class ParityReport:
    available: bool = False
    fidelity_score: float = 0.0
    buy_recall: float = 0.0
    sell_recall: float = 0.0
    status: str = "NOT_VERIFIABLE"
    # Gate fields
    blocking: bool = False       # True if optimization was halted by this report
    drift_analysis: str = ""     # Human-readable explanation of what drifted
    verified_at: str = ""        # Timestamp of verification

def _diagnose_drift(
    pine_buy: np.ndarray,
    pine_sell: np.ndarray,
    python_buy: np.ndarray,
    python_sell: np.ndarray,
    buy_recall: float,
    sell_recall: float,
) -> str:
    """
    Generates a plain-English description of where signal mismatch is occurring.
    Helps the developer know WHICH indicator is drifting without manual debugging.
    """
    lines = []

    if buy_recall < PARITY_THRESHOLD:
        n_pine = int(pine_buy.sum())
        n_matched = int((python_buy[pine_buy.astype(bool)] == 1).sum())
        n_missed = n_pine - n_matched
        n_extra = int((python_buy[~pine_buy.astype(bool)] == 1).sum())
        lines.append(
            f"BUY signal drift ({buy_recall*100:.1f}% recall): "
            f"Pine fired {n_pine} buy signals. Python matched {n_matched}, "
            f"missed {n_missed}, and generated {n_extra} extra signals not in Pine."
        )

    if sell_recall < PARITY_THRESHOLD:
        n_pine = int(pine_sell.sum())
        n_matched = int((python_sell[pine_sell.astype(bool)] == 1).sum())
        n_missed = n_pine - n_matched
        n_extra = int((python_sell[~pine_sell.astype(bool)] == 1).sum())
        lines.append(
            f"SELL signal drift ({sell_recall*100:.1f}% recall): "
            f"Pine fired {n_pine} sell signals. Python matched {n_matched}, "
            f"missed {n_missed}, and generated {n_extra} extra signals not in Pine."
        )

    if not lines:
        return "No drift detected — parity is within acceptable range."

    lines.append(
        "\nLikely causes: (1) Stateful 'var' variable not initialized correctly in Python. "
        "(2) Unknown indicator was translated incorrectly by the Transpiler. "
        "(3) Pine script uses a function that has subtle off-by-one semantics (e.g., ta.barssince)."
    )
    return " ".join(lines)


def run_parity_check(
    df: pd.DataFrame,
    python_buy: np.ndarray,
    python_sell: np.ndarray,
) -> ParityReport:
    """
    Compares Python-reconstructed signals against TradingView-exported signals.

    This is a HARD GATE. If TradingView signal columns are present and parity
    is below 95%, optimization is BLOCKED and the caller must abort.

    Args:
        df: The full OHLCV dataframe (may contain Pine-exported buy/sell columns).
        python_buy: Boolean array of buy signals generated by Python indicator library.
        python_sell: Boolean array of sell signals generated by Python indicator library.

    Returns:
        ParityReport with blocking=True if parity fails the 95% threshold.
    """
    report = ParityReport()

    pine_buy_col  = next((c for c in df.columns if c.lower() in KNOWN_BUY_COLS), None)
    pine_sell_col = next((c for c in df.columns if c.lower() in KNOWN_SELL_COLS), None)

    if not pine_buy_col and not pine_sell_col:
        # No TV signals to compare against — cannot verify, cannot block.
        report.status = "NOT_VERIFIABLE"
        report.drift_analysis = (
            "No TradingView-exported signal columns found in CSV. "
            "Parity cannot be verified. Optimization will proceed unverified. "
            "To enable the Parity Gate, export your Pine Script signals as 'buy'/'sell' "
            "columns in your TradingView data export."
        )
        return report

    report.available = True
    report.verified_at = datetime.utcnow().isoformat()

    pine_buy  = df[pine_buy_col].fillna(0).astype(int).values  if pine_buy_col  else np.zeros(len(df), dtype=int)
    pine_sell = df[pine_sell_col].fillna(0).astype(int).values if pine_sell_col else np.zeros(len(df), dtype=int)

    py_buy_int  = python_buy.astype(int)
    py_sell_int = python_sell.astype(int)

    # Recall: of the bars Pine fired, what % did Python also fire?
    if pine_buy.sum() > 0:
        report.buy_recall = float((py_buy_int[pine_buy == 1] == 1).mean())
    else:
        report.buy_recall = 1.0  # No Pine signals to miss

    if pine_sell.sum() > 0:
        report.sell_recall = float((py_sell_int[pine_sell == 1] == 1).mean())
    else:
        report.sell_recall = 1.0

    report.fidelity_score = (report.buy_recall + report.sell_recall) / 2

    # Gate decision
    if report.fidelity_score >= PARITY_THRESHOLD:
        report.status = "PASS"
        report.blocking = False
        report.drift_analysis = (
            f"Parity PASSED ({report.fidelity_score*100:.1f}%). "
            f"Buy recall: {report.buy_recall*100:.1f}%, "
            f"Sell recall: {report.sell_recall*100:.1f}%. "
            f"Full optimization authorized."
        )
    else:
        report.status = "FAIL"
        report.blocking = True
        report.drift_analysis = _diagnose_drift(
            pine_buy, pine_sell, py_buy_int, py_sell_int,
            report.buy_recall, report.sell_recall,
        )

    return report
